## Login de paciente
POST http://localhost:3000/api/v1/pacientes/login
Content-Type: application/json

{
  "email": "juan@juan.commm",
  "password": "1234"
}

### Crear un nuevo turno (usar el token del login anterior)
POST http://localhost:3000/api/v1/turnos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJqdWFuQGp1YW4uY29tbW0iLCJpYXQiOjE3NDkxMjE0NjEsImV4cCI6MTc1MTE5NTA2MX0.i04YZK8vezNDcIrRPc5ATAU9D3DG4KhWRdvOVVN0OsA

{
  "fecha": "2024-03-20",
  "hora": "14:30",
  "idPaciente": 1
}

### Consultar turnos de un paciente
GET http://localhost:3000/api/v1/turnos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJqdWFuQGp1YW4uY29tbW0iLCJpYXQiOjE3NDkxMjE0NjEsImV4cCI6MTc1MTE5NTA2MX0.i04YZK8vezNDcIrRPc5ATAU9D3DG4KhWRdvOVVN0OsA

### Cancelar un turno
DELETE http://localhost:3000/api/v1/turnos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJqdWFuQGp1YW4uY29tbW0iLCJpYXQiOjE3NDkxMjE0NjEsImV4cCI6MTc1MTE5NTA2MX0.i04YZK8vezNDcIrRPc5ATAU9D3DG4KhWRdvOVVN0OsA



### Login de admin
POST http://localhost:3000/api/v1/admin/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}

### Crear un nuevo turno (como admin)
POST http://localhost:3000/api/v1/admin/turnos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3NDkxMjgyNjMsImV4cCI6MTc1MTIwMTg2M30.0qr9M1LqJZ1dqziYw96dMO-9aO-smrE1oFrYM8Kx2Fw

{
  "fecha": "2024-03-20",
  "hora": "14:30",
  "idPaciente": 1
}

### Listar todos los turnos (como admin)
GET http://localhost:3000/api/v1/admin/turnos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3NDkxMjgyNjMsImV4cCI6MTc1MTIwMTg2M30.0qr9M1LqJZ1dqziYw96dMO-9aO-smrE1oFrYM8Kx2Fw


### Consultar turno por ID (como admin)
GET http://localhost:3000/api/v1/admin/turnos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3NDkxMjgyNjMsImV4cCI6MTc1MTIwMTg2M30.0qr9M1LqJZ1dqziYw96dMO-9aO-smrE1oFrYM8Kx2Fw


### Cancelar un turno (como admin)
DELETE http://localhost:3000/api/v1/admin/turnos/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3NDkxMjgyNjMsImV4cCI6MTc1MTIwMTg2M30.0qr9M1LqJZ1dqziYw96dMO-9aO-smrE1oFrYM8Kx2Fw
